# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Konnected
email: help@konnected.io
description: > # this means to ignore newlines until "baseurl:"
  Alarm Panel Documentation
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://docs.konnected.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  konnected-io
amazon_assoc_asins: B06XSCSBPJ,B0738XJZHT,B010NZV0GE,B000EVYGZA,B06XHGYPLY,B00GF9T3I0,B016W46I9E,B01FSGGJLY,B01M0E6SQM,B00Q2E5IXW,B01N19IK8F,B06XSFCK55
google_analytics: UA-101224545-2

gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']

# Build settings
markdown: kramdown
theme: jekyll-theme-architect
permalink: pretty

defaults:
  - scope:
      path: "assets/images"
    values:
      image: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
